# freeze_smollm2_golden.jl — Phase 10C item B (§LXXII receipt: golden writer).
#
# Produces test/fixtures/smollm2/expected_logits.toml ONCE from Gesso CPU on
# a local SmolLM2-135M snapshot. The golden is a REGRESSION ORACLE, not a
# second stack: the reference is Gesso F64 CPU itself, frozen (§LXXVI item D).
#
# Laws:
#   * never downloads, never talks to huggingface.co — GESSO_SMOLLM2_DIR
#     must point at a COMPLETE local snapshot (config.json + model.safetensors
#     or shard index + vocab.json + merges.txt), or this script refuses.
#   * refuses to overwrite an existing golden unless --force is passed
#     (CI must never regenerate a frozen oracle).
#   * two prefills of the same prompt MUST agree (exact) before anything is
#     written — a nondeterministic oracle is an escalation (10C escalation
#     list), not a golden.
#   * no torch, no PyCall, no Hub client. Pure Gesso + the snapshot files.
#
# Usage (test project — TOML is a test dep, not core, §VII):
#
#   GESSO_SMOLLM2_DIR=/path/to/SmolLM2-135M \
#     julia --project=test test/freeze_smollm2_golden.jl [--force]

using Gesso
using TOML

const REPO_ROOT = normpath(joinpath(@__DIR__, ".."))
const GOLDEN_PATH =
    joinpath(REPO_ROOT, "test", "fixtures", "smollm2", "expected_logits.toml")
const PROMPT = "Hello"                      # the pinned prompt (10C item B)
const VOCAB = 49152                         # SmolLM2-135M vocab_size

_snapshot_complete(dir::AbstractString) =
    isfile(joinpath(dir, "config.json")) &&
    isfile(joinpath(dir, "vocab.json")) &&
    isfile(joinpath(dir, "merges.txt")) &&
    (
        isfile(joinpath(dir, "model.safetensors")) ||
        isfile(joinpath(dir, "model.safetensors.index.json"))
    )

function _refuse(msg::AbstractString)
    println(stderr, "freeze_smollm2_golden: REFUSING — ", msg)
    exit(1)
end

function main()
    force = "--force" in ARGS

    dir = get(ENV, "GESSO_SMOLLM2_DIR", nothing)
    dir === nothing && _refuse(
        "GESSO_SMOLLM2_DIR is unset — point it at a local SmolLM2-135M snapshot (never downloads)",
    )
    isdir(dir) || _refuse("GESSO_SMOLLM2_DIR=$dir is not a directory")
    _snapshot_complete(dir) || _refuse(
        "GESSO_SMOLLM2_DIR=$dir is incomplete — need config.json, model.safetensors (or shard index), vocab.json, merges.txt",
    )

    if isfile(GOLDEN_PATH) && !force
        _refuse(
            "$GOLDEN_PATH already exists — a frozen oracle is never regenerated by accident; pass --force to overwrite deliberately",
        )
    end

    commit = try
        readchomp(setenv(`git rev-parse --short HEAD`; dir=REPO_ROOT))
    catch
        _refuse(
            "could not run `git rev-parse --short HEAD` from $REPO_ROOT — provenance requires the commit",
        )
    end

    println("loading snapshot: $dir")
    model, tensors, cfg = Gesso.load_llama(dir)
    tk = Gesso.load_gpt2_tokenizer(dir)
    ids = Gesso.encode(tk, PROMPT)
    isempty(ids) && _refuse("tokenizer encoded \"$PROMPT\" to zero tokens")
    cfg.vocab_size == VOCAB || _refuse(
        "snapshot vocab_size is $(cfg.vocab_size), expected $VOCAB — this writer is pinned to SmolLM2-135M",
    )

    # the determinism gate: two prefills must agree EXACTLY before anything
    # is frozen. A disagreement here is an escalation (10C escalation list).
    eps, theta = cfg.rms_norm_eps, cfg.rope_theta
    logits_a = Gesso.reference_prefill(model, tensors, ids; eps, theta)
    logits_b = Gesso.reference_prefill(model, tensors, ids; eps, theta)
    if logits_a != logits_b
        Δ = maximum(abs.(logits_a .- logits_b))
        _refuse(
            "two prefills of \"$PROMPT\" DISAGREE (max|Δlogit| = $Δ) — the oracle is not deterministic; stop and escalate (do not freeze)",
        )
    end

    values = collect(Float64, logits_a[:, end])    # last-position logits
    length(values) == VOCAB ||
        _refuse("last-position row has length $(length(values)), expected $VOCAB")
    all(isfinite, values) ||
        _refuse("non-finite logits — refusing to freeze a broken oracle")

    mkpath(dirname(GOLDEN_PATH))
    open(GOLDEN_PATH, "w") do io
        println(
            io,
            "# Frozen SmolLM2-135M golden — Phase 10C item B (§LXXVI item D realized).",
        )
        println(
            io,
            "# Produced ONCE from Gesso CPU (oracle = \"gesso-cpu\") on a local snapshot.",
        )
        println(
            io,
            "# A regression oracle, not a second stack. Reader: test/test_smollm2.jl",
        )
        println(
            io,
            "# (CPU, atol=1e-2) and test/test_cuda_smollm2.jl (device, wider atol).",
        )
        println(
            io,
            "# Regenerate only deliberately: test/freeze_smollm2_golden.jl --force.",
        )
        # Reader law: `golden["values"]` is TOP-LEVEL. TOML has no way back to
        # the root table after a [table] header, so `values` is emitted FIRST
        # and [provenance] closes the file (10C's example order is unparseable
        # as spec'd — the reader contract wins).
        print(io, "values = [")
        for (n, v) in enumerate(values)
            n == 1 || print(io, ", ")
            n % 8 == 0 && print(io, "\n  ")
            print(io, repr(v))
        end
        println(io, "]")
        println(io)
        println(io, "[provenance]")
        println(io, "oracle = \"gesso-cpu\"")
        println(io, "prompt = \"$PROMPT\"")
        println(io, "position = \"last\"")
        println(io, "dtype = \"Float64\"")
        println(io, "vocab_size = $VOCAB")
        println(io, "model = \"HuggingFaceTB/SmolLM2-135M\"")
        println(io, "gesso_commit = \"$commit\"")
        # snapshot identified by files present, never a Hub revision fetch
        println(
            io,
            "snapshot = \"local GESSO_SMOLLM2_DIR (config.json + model.safetensors + vocab.json + merges.txt)\"",
        )
    end

    roundtrip = TOML.parsefile(GOLDEN_PATH)
    @assert get(get(roundtrip, "provenance", Dict()), "oracle", "") == "gesso-cpu"
    @assert Float64.(roundtrip["values"]) == values    # TOML round-trip is exact

    println("frozen: $GOLDEN_PATH")
    println("  prompt     = \"$PROMPT\" (tokens: $(join(ids, ",")))")
    println(
        "  values     = $(length(values)) Float64 ($(round(stat(GOLDEN_PATH).size / 1024; digits=1)) KiB)",
    )
    println("  commit     = $commit")
    println("  determinism: two prefills agreed exactly")
end

main()
