# Independent CPU gate; the supplied receipt must be generated by reference_hf.py.
using JSON
using SHA
using Test

@testset "Independent HF/PyTorch real-model parity (Regime I arm 1)" begin
    path = get(ENV, "GESSO_HF_REFERENCE", "")
    if isempty(path)
        @test _skip("GESSO_HF_REFERENCE unset — independent HF reference not supplied")
    else
        ref = JSON.parsefile(path)
        @test ref["schema"] == "gesso-hf-reference-v1"
        @test ref["oracle"] == "hf-pytorch-eager"
        @test ref["device"] == "cpu"
        @test ref["dtype"] == "float32"
        @test ref["atol"] == 1e-2
        @test ref["rtol"] == 0
        @test ref["max_new_tokens"] == 8
        @test length(ref["cases"]) == 3
        dir = ENV["GESSO_SMOLLM2_DIR"]
        hashes = ref["checkpoint_sha256"]
        @test all(
            haskey(hashes, name) for
            name in ("config.json", "model.safetensors", "vocab.json", "merges.txt")
        )
        for (name, digest) in hashes
            @test basename(name) == name
            actual = open(sha256, joinpath(dir, name))
            @test bytes2hex(actual) == digest
        end
        @test [case["prompt"] for case in ref["cases"]] == ["Hello", "The quick brown fox", "Julia is a programming language."]
        model, tensors, cfg = Gesso.load_llama(dir)
        tokenizer = Gesso.load_gpt2_tokenizer(dir)
        eos_id = Int(JSON.parsefile(joinpath(dir, "config.json"))["eos_token_id"])
        for case in ref["cases"]
            @testset "$(case["prompt"])" begin
                ids = Gesso.encode(tokenizer, case["prompt"])
                @test ids == Int.(case["prompt_ids"])
                expected = Float64.(case["last_logits"])
                @test length(expected) == cfg.vocab_size
                oracle = Gesso.reference_prefill(
                    model,
                    tensors,
                    ids;
                    eps=cfg.rms_norm_eps,
                    theta=cfg.rope_theta,
                )
                session = Gesso.Session(
                    model,
                    tensors;
                    context_length=64,
                    eos_token_id=eos_id,
                    tokenizer=tokenizer,
                    eps=cfg.rms_norm_eps,
                    theta=cfg.rope_theta,
                )
                engine = Gesso.prefill!(session, ids)
                delta = maximum(abs.(oracle[:, end] .- expected))
                @info "HF parity" prompt=case["prompt"] max_abs_delta=delta
                @test all(isfinite, oracle)
                @test delta <= 1e-2
                @test maximum(abs.(engine[:, end] .- expected)) <= 1e-2
                @test Gesso.generate(session, ids; max_new_tokens=8) ==
                      Int.(case["generated_ids"])
                @test Gesso.reference_generate(
                    model,
                    tensors,
                    ids;
                    max_new_tokens=8,
                    eps=cfg.rms_norm_eps,
                    theta=cfg.rope_theta,
                ) == Int.(case["generated_ids"])
            end
        end
    end
end
