# Phase 3 item D (§LXXVI exit): REAL SmolLM2-135M logit match — the gate.
#
# Laws (§LXXVI):
#   * `make test` never downloads and never talks to huggingface.co. The
#     snapshot must already exist locally at GESSO_SMOLLM2_DIR.
#   * CI stays green on a machine that has never seen SmolLM2 weights:
#     without the env var this file is ONE named skip, nothing more.
#   * The reference vector is produced ONCE from Gesso itself on the
#     snapshot (oracle = "gesso-cpu"), then frozen — a regression oracle,
#     not a second stack. It is NEVER regenerated by a test run.
#   * No golden file is faked. Items A, B, C landed green; this file carries
#     the skip until a snapshot exists on the machine that runs it.

using Test: AbstractTestSet, Broken, get_testset, record

using TOML

const SMOLLM2_DIR = get(ENV, "GESSO_SMOLLM2_DIR", nothing)
const GOLDEN_PATH = joinpath(@__DIR__, "fixtures", "smollm2", "expected_logits.toml")

# the pinned prompt: exactly "Hello" — the tokenizer emits whatever the
# snapshot's vocab gives it; no synthetic BOS (base model, no chat template)
const SMOLLM2_PROMPT = "Hello"

# the sanctioned skip: a Broken(:skipped) record on the ACTIVE testset —
# visible in the summary, green in the harness, named with the env var
# (§LXXVI: skip with a message that names the env var)
function _skip(msg::AbstractString)
    ts = get_testset()
    ts isa AbstractTestSet && record(ts, Broken(:skipped, String(msg)))
    return true
end

@testset "SmolLM2-135M real-model gate (§LXXVI item D)" begin
    if SMOLLM2_DIR === nothing
        @test _skip(
            "GESSO_SMOLLM2_DIR is unset — set it to a local snapshot of HuggingFaceTB/SmolLM2-135M (config.json + model.safetensors or shard index + vocab.json + merges.txt) to run the real-model gate",
        )
    elseif !isdir(SMOLLM2_DIR)
        @test _skip(
            "GESSO_SMOLLM2_DIR=$SMOLLM2_DIR is not a directory — the gate never downloads (§LXXVI)",
        )
    elseif !isfile(joinpath(SMOLLM2_DIR, "config.json")) ||
           !isfile(joinpath(SMOLLM2_DIR, "vocab.json")) ||
           !isfile(joinpath(SMOLLM2_DIR, "merges.txt")) ||
           (
               !isfile(joinpath(SMOLLM2_DIR, "model.safetensors")) &&
               !isfile(joinpath(SMOLLM2_DIR, "model.safetensors.index.json"))
           )
        @test _skip(
            "GESSO_SMOLLM2_DIR=$SMOLLM2_DIR is incomplete — need config.json, model.safetensors (or shard index), vocab.json, merges.txt",
        )
    else
        # ---- the real gate -------------------------------------------------
        model, tensors, cfg = Gesso.load_llama(SMOLLM2_DIR)
        tk = Gesso.load_gpt2_tokenizer(SMOLLM2_DIR)

        # composition sanity: the released config facts (§LXXVI pinned table)
        @test cfg.num_hidden_layers == 30
        @test cfg.num_attention_heads == 9
        @test cfg.num_key_value_heads == 3
        @test cfg.hidden_size == 576
        @test cfg.vocab_size == 49152
        @test cfg.rms_norm_eps == 1e-5
        @test cfg.rope_theta == 100000.0
        @test model.blocks[1].attention.n_kv_heads == 3

        # encode the pinned prompt and prefill with the config's constants
        ids = Gesso.encode(tk, SMOLLM2_PROMPT)
        @test isempty(ids) == false
        logits = Gesso.reference_prefill(
            model,
            tensors,
            ids;
            eps=cfg.rms_norm_eps,
            theta=cfg.rope_theta,
        )
        @test size(logits) == (49152, length(ids))

        # greedy generation: deterministic, consistent with prefill argmax
        gen = Gesso.reference_generate(
            model,
            tensors,
            ids;
            max_new_tokens=4,
            eps=cfg.rms_norm_eps,
            theta=cfg.rope_theta,
        )
        @test gen[1:length(ids)] == ids
        @test gen == Gesso.reference_generate(
            model,
            tensors,
            ids;
            max_new_tokens=4,
            eps=cfg.rms_norm_eps,
            theta=cfg.rope_theta,
        )

        # frozen-reference comparison: last-position logits vs the golden file
        if isfile(GOLDEN_PATH)
            golden = TOML.parsefile(GOLDEN_PATH)
            prov = get(golden, "provenance", Dict{String, Any}())
            @test get(prov, "oracle", "") == "gesso-cpu"
            # 10C item B format: one compact `values` array of 49152 Float64s
            # (provenance table + values; the old {v=…} table shape is gone)
            values = Float64.(golden["values"])
            @test length(values) == 49152
            # §LXXVI tolerance: atol=1e-2, rtol=0 — f64 Gesso vs frozen f64 Gesso
            last = logits[:, end]
            @test all(
                i -> isapprox(last[i], values[i]; atol=1e-2, rtol=0.0),
                eachindex(values),
            )
        else
            # snapshot present but golden not frozen: first-run instruction,
            # NOT a faked file
            @test _skip(
                "snapshot present but test/fixtures/smollm2/expected_logits.toml is not frozen yet — prefill once on this snapshot and commit the result with provenance oracle = \"gesso-cpu\"",
            )
        end
    end
end
